version: '3.3'

services:
  minio:
    container_name: minio
    hostname: minio-test
    network_mode: host
    image: quay.io/minio/minio
    restart: always
    command:
      - server
      - /data
      - "--console-address"
      - ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9001" ]
      interval: 30s
      timeout: 10s
      retries: 5
  prepare_buckets:
    container_name: minio-setup
    image: quay.io/minio/minio
    network_mode: host
    depends_on:
      minio:
        condition: service_healthy
    entrypoint:
      - "/bin/sh"
      - "-c"
      - |
        mc alias set e2e "http://localhost:9000" minioadmin minioadmin
        mc admin info e2e
        mc mb e2e/synapse-archive

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    network_mode: host
    command:
      - "azurite-blob"
      - "--blobHost"
      - "localhost"
      - "--blobPort"
      - "10001"
      - "--skipApiVersionCheck"
  create-cdm-container:
    image: python:3.11-slim-bookworm
    network_mode: host
    depends_on:
      - azurite
    volumes:
      - ./populate-cdm-container.py:/populate-cdm-container.py
    command: [ "/bin/sh", "-c", "pip install azure-storage-blob requests && python /populate-cdm-container.py" ]
