name: Validate code format

on:
  pull_request:
    branches:
      - main

jobs:
  validate_code:
    name: Validate code format
    runs-on: ubuntu-latest

    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.x'
          architecture: 'x64'

      - name: Install Poetry and dependencies
        uses: SneaksAndData/github-actions/install_poetry@v0.1.9
        with:
          install_extras: "all"
      - name: Black
        shell: bash
        run: |
          set -e
          poetry run black . --check --diff
